# name: My First GitHub Actions

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         python-version: [3.8, 3.9]

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: ${{ matrix.python-version }}

#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install pytest

#     - name: Run tests
#       run: |
#         cd src
#         python -m pytest addition.py

name: My First GitHub Actions

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if needed

jobs:
  build:
    runs-on: self-hosted  # Uses a self-hosted runner   and ubuntu-latest for github hosted

    strategy:
      matrix:
        python-version: [3.8, 3.9] # pipeline executed in 2 version

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # it is not configuration,it is plugins

    - name: Set up Python
      uses: actions/setup-python@v2  # python plugins
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py

